
[opener]
edit = [
{ run = 'nvim %*', block = true, desc = "nvim",  for = "windows" },
{ run = 'nvim "$@"', block = true, desc = "nvim", for = "unix" }
]

open = [
{ run = 'nvim %*', block = true, desc = "nvim",  for = "windows" },
{ run = "nvim %F", block = true, desc = "nvim", for = "unix" }
]

